### ISSUE TITLE
Create Google user protected area

### ISSUE THREAD

**Issue by jaredhasenklein** [Milken-Computer-Science/milkenknightsdotcom#15]
Two areas should be created, if possible.

**Top priority**
`/scouting/2018` should be restricted to a list of Google users (e.g. jhasenklein@gmail.com, jhasen-klein669@milkenschool.org, etc.). @aswerdlow935 You can just protect a Hello World page for now and I'll add the content later

**Low priority**
`/members` should be restricted to milkenschool.org users. Same concept as above - empty area and I will add content later.

**Comment by alexanderswerdlow** [comment]
Now just password protected
